//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int IdAdministrador { get; set; }
        public string Usuario { get; set; }
        public int Contraseña { get; set; }
        public string Correo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Celular { get; set; }
        public string Estado { get; set; }
    }
}
